version: '3.7'
services:
  app:
    image: bakrep-web
    build: 
      context: ..
    ports:
      - "5173:5173"
    volumes:
      - ../:/srv/app/


networks:
  default:
    name: deployments_default
    external: true
