<template>
  <div class="container">
    <h2>About Bakrep</h2>
    <p>
        BakRep is a searchable web repository for bacterial genomes and standardized characterizations. This interactive website will provide researchers with a flexible search engine to query the repository. Information regarding the website and the opportunity for technical issues and bug reports are provided via <a href="https://github.com/ag-computational-bio/bakrep-web/" target="_blank">GitHub</a>.
    </p>

    <p>
      The BakRep worflow conducted taxonomic classification, subtyping and annotation of the assemblies generated by Blackwell et al., 2021. Information regarding the workflow are provided via GitHub.
    </p>

    <p>
      General contact and questions: <a href="mailto:bakrep@computational.bio.uni-giessen.de">bakrep@computational.bio.uni-giessen.de</a>
    </p>
  </div>
</template>
